import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {
  Radio,
  Dropdown,
  Label,
  Button,
  Card,
  Hero,
} from "@hilliegithub/mycomponent-library";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className="App-container">
          <h1>Here are my component:</h1>
          <Radio options={["Yes", "No", "Maybe"]} bgColor="#F04520" />
          <Dropdown options={["yes", "no", "maybe"]} bgColor="#b19b11" />
          <Dropdown options={["fakeoptions", "maybe"]} disabled={true} />
          <div className="spacing">
            <Label value="This is my lable component" bgColor="#3f3912" />
            <Label value="Disable lable component" disabled bgColor="#3f3912" />
          </div>
          <div className="spacing">
            <Button text="MyButton" bgColor="#3f3912" />
            <Button text="Disabled" bgColor="#3f3912" disabled={true} />
            {/* FONT COLOR */}
          </div>
          <div className="spacing">
            <Card
              cardTitle="HTML CARD"
              img="https://images.unsplash.com/photo-1518773553398-650c184e0bb3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80"
              cardDesc="Does this look like html? what do you think?"
              bgColor="#b19b11"
            />
            {/* <Dropdown options={["yes", "no", "maybe"]} bgColor="#b19b11" />
          <Dropdown options={["fakeoptions", "maybe"]} disabled={true} /> */}
          </div>
          <div className="spacing">
            {/* <Text value="Text component" disabled={false} bgColor="#b19b11" /> */}
            <Radio
              options={["Yes", "No", "Maybe"]}
              disabled={false}
              bgColor="F04520"
            />
          </div>
          <div className="spacing">
            <Hero
              HeroText="Mac setup"
              src="https://images.unsplash.com/photo-1585076641399-5c06d1b3365f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80"
            />
          </div>
          <div className="spacing"></div>
          <div className="spacing"></div>
        </div>
      </main>
    </>
  );
}
